import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Chart from './component/chart';
import PieChart from './component/piechart';
import LineChart from './component/linechart';
import BarChart from './component/barchart2datasets'


class App extends Component {

    constructor(){
    super();
    this.state = {
      chartData:{}
    }
  }

  componentWillMount(){
    this.getChartData();
  }

   getChartData(){


    // Ajax calls here
    this.setState({
      chartData:{
        labels: ['North America', 'USA','Latin America', 'Europe, middle-east, Africa', 'China', 'Asia-Pacific'],
        datasets:[
          {
            label:'revenue YoY (Bn)',
            data:[
              23.8,
              22.0,
              4.0,
              20.5,
              22.2,
              43.1
            ],
            backgroundColor:[
              'rgba(255, 99, 132, 0.6)',
              'rgba(54, 162, 235, 0.6)',
              'rgba(255, 206, 86, 0.6)',
              'rgba(75, 192, 192, 0.6)',
              'rgba(153, 102, 255, 0.6)',
              'rgba(255, 159, 64, 0.6)',
              'rgba(255, 99, 132, 0.6)'
            ]
          }
        ]
      }
    });
  }

  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1>GLOBAL GAME MARKET: A CHART VIEW</h1>
          
        </div>
        <h2>THE GLOBAL GAMES MARKET WILL REACH $108.9 BILLION IN 2017 WITH MOBILE TAKING 42%</h2>
        <p>2.2 billion gamers across the globe are expected to generate $108.9 billion in game revenues in 2017. This represents an increase of $7.8 billion, or 7.8%, from the year before. Digital game revenues will account for $94.4 billion or 87% of the global market. Mobile is the most lucrative segment, with smartphone and tablet gaming growing 19% year over year to $46.1 billion, claiming 42% of the market. In 2020, mobile gaming will represent just more than half of the total games market. The PC and console game markets will generate $29.4 billion and $33.5 billion in 2017, respectively.

Asia-Pacific is by far the largest region, with China expected to generate $27.5 billion, or one-quarter of all revenues in 2017. Newzoo expects the global market to grow at a CAGR of +6.2% toward 2020 to reach $128.5 billion. Based on its review of final 2016 financial results of more than 70 public companies, Newzoo also upped its final take on 2016 by $1.1 billion to $101.1 billion. Mobile games performed even better than expected, especially in China, while the PC games market performed worse than anticipated in Newzoo’s previous quarterly update.</p>
       <Chart chartData={this.state.chartData} location="World Wide" legendPosition="bottom"/> 


       <h2>CHINA TO GENERATE ONE-QUARTER OF GAME REVENUES WORLDWIDE</h2>
       <p>The APAC territories will generate $51.2 billion this year, or 47% of total global game revenues. This growth represents a 9.2% year-on-year increase. China alone will take one-quarter of all global game revenues, reaching $27.5 billion this year, well ahead of the U.S., which is estimated to reach $25.1 billion. Most of China’s growth will come from mobile gaming, with Tencent and NetEase leading the way. Mobile gaming revenues from these two companies alone reached $7.7 billion in 2016. As a result, we increased our previous 2016 mobile revenue estimates for China from $10.0 billion to $11.2 billion. We expect growth to continue toward $14.6 billion in 2017 for China alone. The fastest-growing region in the coming years will be Rest of Asia (without China, Japan, and Korea), with total game revenues growing to $10.5 billion in 2020, up from $4.5 billion last year.

North America is the second-largest region, with estimated revenues of $27.0 billion in 2017, a year-on-year increase of 4.0%. Most of this growth will come from smartphone gaming, a mature market, but certainly not saturated. Growth is fueled by a combination of a higher share of spenders as well as average spend per paying gamer. We see the same trend in EMEA, which we expect to reach $26.2 billion in 2017. Latin America will grow to $4.4. billion in game revenues this year.</p>
        <PieChart/>

        <h2> Chinese  vs. USA industry. China leading by far.</h2>
        <p>The 600 million gamers in China generated $24.6 billion of the industry's $101.1 billion global market value over 2016, just ahead of the U.S.’s $24.1 billion. In 2015, the global games industry was worth $91.8 billion according to data from research house Newzoo. A notable contributor to the growth has been Apple's mobile app store in China. In 2016, China accounted for 31 percent of the total $18 billion generated by games on iOS, compared with just 3 percent of the $2.4 billion total in 2012. </p>

        <LineChart/>
        <h2>CHINESE GIANTS TENCENT AND NETEASE SEE LARGEST GROWTH</h2>
        <p>Tencent cemented its position as the #1 gaming company in the world, recording a staggering 50% increase in revenues to reach $7.4 billion in the first half of 2017. This is an additional $2.4 billion compared to the same period in 2016. Tencent’s smartphone games yielded more earnings than its PC games for the first time in the second quarter of 2017. Including Supercell’s revenues of more than $1 billion, Tencent’s revenues were almost double that of the #2 company in the ranking, Sony. Tencent’s robust growth was driven by the popularity of Honor of Kings, with 200 million players in China alone. Tencent is looking to sustain its growth in several ways: the release of Honor of Kings in Europe and the United States, the launch of gaming platform WeGame, and the launch of a free-to-play version of Rocket League in China.

NetEase also continued to perform very well in China and grew 53% year on year in H1 2017. Last year, we concluded that NetEase was a strong contender for a top five position in 2017. While they didn’t get there in H1, the ongoing success of Fantasy Westward Journey Online, its successor Fantasy Westward Journey Online 2, plus newer titles Ghost Story and Onmyoji, may well propel it into the global top five for the full year.

Sony ranks as #2 overall yet remains the largest company in terms of console revenues. Sony’s 25% growth year on year was primarily due to an increase in sales through the PlayStation network. Microsoft retained its #4 position, but continued to grow at a slower pace than Sony.</p>
        <BarChart/>
      </div>
    );
  }
}


export default App;